services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper1
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_PEERPORT: 2888
      ZOOKEEPER_LEADERPORT: 3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
      ZOOKEEPER_SERVER_ID: 1
    healthcheck:
      test: ["CMD-SHELL", "(echo > /dev/tcp/zookeeper1/2181) &>/dev/null && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 50s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    
  zookeeper2:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper2
    container_name: zookeeper2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_PEERPORT: 2888
      ZOOKEEPER_LEADERPORT: 3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
      ZOOKEEPER_SERVER_ID: 2
    healthcheck:
      test: ["CMD-SHELL", "(echo > /dev/tcp/zookeeper2/2181) &>/dev/null && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 50s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  zookeeper3:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper3
    container_name: zookeeper3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_PEERPORT: 2888
      ZOOKEEPER_LEADERPORT: 3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
      ZOOKEEPER_SERVER_ID: 3
    healthcheck:
      test: ["CMD-SHELL", "(echo > /dev/tcp/zookeeper3/2181) &>/dev/null && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 50s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    depends_on:
      zookeeper1:
        condition: service_healthy
      zookeeper2:
        condition: service_healthy
      zookeeper3:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_LOG_DIRS: /var/log/kafka
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SCHEMA_REGISTRY_URL: 8081
    healthcheck:
      test: ["CMD-SHELL", "(echo > /dev/tcp/kafka1/9092) &>/dev/null && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  kafka2:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_LOG_DIRS: /var/log/kafka
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SCHEMA_REGISTRY_URL: 8081

    healthcheck:
      test: ["CMD-SHELL", "(echo > /dev/tcp/kafka2/9093) &>/dev/null && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      kafka1:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  kafka3:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_LOG_DIRS: /var/log/kafka
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SCHEMA_REGISTRY_URL: 8081

    healthcheck:
      test: ["CMD-SHELL", "(echo > /dev/tcp/kafka3/9094) &>/dev/null && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      kafka2:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9093,PLAINTEXT://kafka3:9094
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka3:9094"
    depends_on:
      - "kafka3"
  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml"
  grafana:
    image: grafana/grafana:10.1.10
    ports:
      - "3000:3000"

networks:
  internal-network:
    driver: bridge

